export const LOCATION_PERMISSION = 'LOCATION_PERMISSION'
export const CURRENT_LOCATION = 'CURRENT_LOCATION'
export const LAST_LOCATION = 'LAST_LOCATION'
export const REVERSE_GEOCODED_LOCATION = 'REVERSE_GEOCODED_LOCATION'
