export const TAB_NAVIGATION_HEIGHT = 50
export const HOME_TAB_BOTTOM_NAVIGATION_HEIGHT_WITH_INSETS = 100
export const HOME_TAB_BOTTOM_NAVIGATION_HEIGHT = 70
export const HOME_TAB_TOP_NAIGATION_HEIGHT = 105
