export const LOCATION_TASK_NAME = 'LOCATION_TASK_NAME'
export const GEOFENCING_LOCATION_TASK_NAME = 'GEOFENCING_LOCATION_TASK_NAME'
export const BACKGROUND_NOTIFICATION_TASK = 'BACKGROUND-NOTIFICATION-TASK'
